config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout' }, as: 'user_sessions'
  root to: 'pages#home'

  resources :genres
  resources :users
  resources :authors
  resources :reader_cards
  resources :libraries
  resources :books
  get '/home', to: 'pages#home'
  get 'downloads/csv', to: 'downloader#csv', as: 'downloader_csv'
  get 'downloads/pdf', to: 'downloader#pdf', as: 'downloader_pdf'
  get '/libraries/:id/download_report', to: 'downloader#pdf_library', as: 'downloader_pdf_library'
  get '/users/:id/download_report', to: 'downloader#pdf_user', as: 'downloader_pdf_user'

end

app/models/reader_card.rb
class ReaderCard < ApplicationRecord
  belongs_to :user
  belongs_to :library
  has_many :books
  validates :library, presence: true
  validates :user, presence: true, uniqueness: { scope: [:library] }

  def self.add_reader_card(user_id, library_id)
    user = User.find(user_id)
    library = Library.find(library_id)
    reader_card = ReaderCard.new(user: user, library: library)
    if reader_card.valid?
      reader_card.save
      ReaderCard.last
    else
      # Обработка ошибок валидации
      puts reader_card.errors.full_messages
      nil
    end
  end

  def self.update_reader_card (user_id, library_id, id)
    library = Library.find(library_id)
    user = User.find(user_id)
    reader_card_id = ReaderCard.find(id)
    reader_card = ReaderCard.new(user: user, library: library)
    if reader_card.valid?
      reader_card_id.update(user: user, library: library)
      return reader_card_id
    else
      # Обработка ошибок валидации
      puts reader_card.errors.full_messages
      nil
    end
  end

  def self.delete_reader_card_id (id)
    reader_card_id = ReaderCard.find(id)
    reader_card_id.delete
  end

  def name_with_library
    "#{id} - #{user.name} (#{library.name})"
  end

end

app/controllers/reader_cards_controller.rb
class ReaderCardsController < ApplicationController
  before_action :set_reader_card, only: %i[show edit]

  def index
    @reader_cards = ReaderCard.all
  end

  def show; end

  def new
    @libraries = Library.all
    @users = User.all
    @reader_card = ReaderCard.new
  end

  def create
    @reader_card = ReaderCard.add_reader_card(reader_card_params[:user_id], reader_card_params[:library_id])
    if @reader_card
      redirect_to @reader_card
    else
      flash.now[:alert] = 'This reader_card already exists!'
      @reader_card = ReaderCard.new
      @users = User.all
      @libraries = Library.all
      render :new
    end
  end

  def edit
    @users = User.all
    @libraries = Library.all
  end

  def update
    @reader_card = ReaderCard.update_reader_card(reader_card_params[:user_id], reader_card_params[:library_id],
                                                 params[:id])
    if @reader_card
      redirect_to @reader_card
    else
      flash.now[:alert] = 'This reader_card already exists!'
      set_reader_card
      @users = User.all
      @libraries = Library.all
      render :edit
    end
  end

  def destroy
    ReaderCard.delete_reader_card_id(params[:id])
    redirect_to reader_cards_path
  end

  private

  def reader_card_params
    params.require(:reader_card).permit(:user_id, :library_id)
  end

  def set_reader_card
    @reader_card = ReaderCard.find(params[:id])
  end
end

app/helpers/reader_cards_helper.rb
module ReaderCardsHelper
end

app/views/reader_cards/edit.html.erb
<h1>Edit Reader Card</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @reader_card, url: reader_card_path(@reader_card), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @users, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.collection_select :library_id, @libraries, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reader_cards/index.html.erb
<h1>Reader Cards</h1>
</p><%= link_to 'Back', home_path %></p>
<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Library</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @reader_cards.each do |reader_card| %>
    <tr>
      <td><%= reader_card.user.name %></td>
      <td><%= reader_card.library.name %></td>
      <td>
        <%= link_to 'Show', reader_card %>
        <%= link_to 'Edit', edit_reader_card_path(reader_card) %>
        <%= button_to 'Destroy', reader_card, method: :delete%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reader Card', new_reader_card_path %>

app/views/reader_cards/new.html.erb
<h1>New Reader Card</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @reader_card, url: reader_cards_path) do |form| %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @users, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.collection_select :library_id, @libraries, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reader_cards/show.html.erb
<h1>Reader Card Details</h1>

<table>
  <tr>
    <td><strong>User:</strong></td>
    <td><%= @reader_card.user.name %></td>
  </tr>
  <tr>
    <td><strong>Library:</strong></td>
    <td><%= @reader_card.library.name %></td>
  </tr>
  <tr>
    <td><strong>Books:</strong></td>
    <td>
      <% if @reader_card.books.any? %>
        <ul>
          <% @reader_card.books.each do |book| %>
            <li><%= book.title %></li>
          <% end %>
        </ul>
      <% else %>
        <p>No books yet</p>
      <% end %>
    </td>
  </tr>
</table>

<p><%= link_to 'Edit', edit_reader_card_path(@reader_card) %></p>
<p><%= link_to 'Back', reader_cards_path %></p>