config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout' }, as: 'user_sessions'
  root to: 'pages#home'

  resources :genres
  resources :users
  resources :authors
  resources :reader_cards
  resources :libraries
  resources :books
  get '/home', to: 'pages#home'
  get 'downloads/csv', to: 'downloader#csv', as: 'downloader_csv'
  get 'downloads/pdf', to: 'downloader#pdf', as: 'downloader_pdf'
  get '/libraries/:id/download_report', to: 'downloader#pdf_library', as: 'downloader_pdf_library'
  get '/users/:id/download_report', to: 'downloader#pdf_user', as: 'downloader_pdf_user'

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books
  validates :name, presence: true, uniqueness: { scope: [:birthdate] }
  validates :birthdate, presence: true

  def self.add_author(name, birthdate)
    create_updated = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    author = Author.new(name: name, birthdate: birthdate)
    if author.valid?
      connection.execute("INSERT INTO authors (name, birthdate, created_at, updated_at) VALUES ('#{name}', '#{birthdate}', '#{create_updated}','#{create_updated}')")
      Author.last
    else
      # Обработка ошибок валидации
      puts author.errors.full_messages
      nil
    end
  end

  def self.update_author(name, birthdate, id)
    updated_at = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    author = Author.new(name: name, birthdate: birthdate)
    if author.valid?
      connection.execute("UPDATE authors SET name = '#{name}', birthdate = '#{birthdate}', updated_at = '#{updated_at}' WHERE id = #{id}")
      Author.find(id)
      # author_id = connection.execute("SELECT last_insert_rowid()")[0][0]
      # find(author_id)
    else
      # Обработка ошибок валидации
      puts author.errors.full_messages
      nil
    end
  end

  def self.delete_author_id (id)
    connection.execute("DELETE FROM authors WHERE id = #{id}")
  end

  def self.book_counts
    result = Author.find_by_sql("SELECT * FROM author_book_counts")
    result.each do |row|
      puts "Author #{row.name} has #{row.book_count} books"
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit]

  def index
    @authors = Author.all
  end

  def show; end

  def new
    @author = Author.new
  end

  def create
    @author = Author.add_author(author_params[:name], author_params[:birthdate])
    if @author
      redirect_to @author
    else
      flash.now[:alert] = 'This author already exists!'
      @author = Author.new
      render :new
    end
  end

  def edit; end

  def update
    @author = Author.update_author(author_params[:name], author_params[:birthdate], params[:id])
    if @author
      redirect_to @author
    else
      flash.now[:alert] = 'This author already exists!'
      set_author
      render :edit
    end
  end

  def destroy
    Author.delete_author_id(params[:id])
    redirect_to authors_path
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :birthdate)
  end
end

app/views/authors/edit.html.erb
<h1>Edit author</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @author, url: author_path) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :birthdate %><br>
    <%= form.date_field :birthdate,{ value: @author.birthdate,
                                    class: 'form-control',
                                    required: true,
                                    format: '%d.%m.%Y' } %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/index.html.erb
<h1>All authors</h1>
</p><%= link_to 'Back', home_path %></p>

<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>
<%= link_to 'New author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<%= form_with(model: @author, url: authors_path) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :birthdate %><br>
    <%= form.date_field :birthdate,{ value: @birthdate,
                                     class: 'form-control',
                                     required: true,
                                     format: '%d.%m.%Y' } %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<p>Birthdate: <%= @author.birthdate %></p>

<%= link_to 'List author', authors_path %>
<%= link_to 'Edit author', edit_author_path%>
<%= button_to "Destroy this author", @author, method: :delete %>