config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout' }, as: 'user_sessions'
  root to: 'pages#home'

  resources :genres
  resources :users
  resources :authors
  resources :reader_cards
  resources :libraries
  resources :books
  get '/home', to: 'pages#home'
  get 'downloads/csv', to: 'downloader#csv', as: 'downloader_csv'
  get 'downloads/pdf', to: 'downloader#pdf', as: 'downloader_pdf'
  get '/libraries/:id/download_report', to: 'downloader#pdf_library', as: 'downloader_pdf_library'
  get '/users/:id/download_report', to: 'downloader#pdf_user', as: 'downloader_pdf_user'

end

app/models/library.rb
class Library < ApplicationRecord
  has_many :books
  has_many :reader_cards
  validates :location, presence: true
  validates :name, presence: true, uniqueness: {  scope: [:location, :year_of_creation]}
  validates :year_of_creation, presence: true
  validates :street_address, presence: true
  validates :zip_code, presence: true
  has_one_attached :image

  def self.add_library(name, location, year_of_creation)
    create_updated = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    library = Library.new(name: name, location: location, year_of_creation: year_of_creation)
    if library.valid?
      connection.execute("INSERT INTO libraries (name, location, created_at, updated_at, year_of_creation) VALUES ('#{name}', '#{location}', '#{create_updated}','#{create_updated}', '#{year_of_creation}')")
      Library.last
    else
      # Обработка ошибок валидации
      puts library.errors.full_messages
      nil
    end
  end

  def self.update_library(name, location, year_of_creation, id)
    updated_at = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    library = Library.new(name: name, location: location, year_of_creation: year_of_creation)
    if library.valid?
      connection.execute("UPDATE libraries SET name = '#{name}', location = '#{location}', year_of_creation = '#{year_of_creation}', updated_at = '#{updated_at}' WHERE id = #{id}")
      return Library.find(id)
    else
      # Обработка ошибок валидации
      puts library.errors.full_messages
      nil
    end
  end

  def self.delete_library_id (id)
    connection.execute("DELETE FROM libraries WHERE id = #{id}")
  end

  def self.book_counts
    result = Library.find_by_sql("SELECT * FROM library_book_counts")
    result.each do |row|
      puts "Library #{row.library_name} has #{row.book_count} books"
    end
  end

  # def self.list_libraries
  #     Library.find_by_sql("
  #   SELECT libraries.id, libraries.name, COUNT(DISTINCT books.id) AS books_count, COUNT(DISTINCT genres.id) AS genres_count
  #   FROM libraries
  #   LEFT JOIN books ON books.library_id = libraries.id
  #   LEFT JOIN book_genres ON book_genres.book_id = books.id
  #   LEFT JOIN genres ON genres.id = book_genres.genre_id
  #   GROUP BY libraries.id, libraries.name
  # ")
  # end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update]

  def index
    @libraries = LibrariesQuery.main_sort(params)
    @sort_by = params[:sort_by]
    @name = params[:name]
  end

  def show
    @books = @library.books
    @reader_cards = @library.reader_cards
  end

  def new
    @library = Library.new
  end

  def create
    # @library = Library.add_library(library_params[:name], library_params[:location], library_params[:year_of_creation])
    @library = Library.new(name: library_params[:name], location: library_params[:location], year_of_creation: library_params[:year_of_creation],street_address: library_params[:street_address], zip_code: library_params[:zip_code], image: library_params[:image])
    if @library.save
      redirect_to @library
    else
      flash.now[:alert] = 'This library already exists!'
      @library = Library.new(name: library_params[:name], location: library_params[:location], year_of_creation: library_params[:year_of_creation], image: library_params[:image])
      render :new
    end
  end

  def edit; end

  def update
    # @library = Library.update_library(library_params[:name], library_params[:location], library_params[:year_of_creation], params[:id])
    if @library.update(name: library_params[:name], location: library_params[:location], year_of_creation: library_params[:year_of_creation], street_address: library_params[:street_address], zip_code: library_params[:zip_code], image: library_params[:image])
      redirect_to @library
    else
      flash.now[:alert] = 'This library already exists!'
      set_library
      render :edit
    end
  end

  def destroy
    Library.delete_library_id(params[:id])
    redirect_to libraries_path
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end

  def library_params
    params.require(:library).permit(:name, :location, :year_of_creation, :street_address, :zip_code, :image)
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/edit.html.erb
<h1>Edit Library</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @library, url: library_path(@library), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :year_of_creation %>
    <%= form.text_field :year_of_creation %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
    <%#= form.text_field :year_of_creation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/index.html.erb
<h1>Libraries</h1>
</p><%= link_to 'Back', home_path %></p>
<!--<ul>-->
  <%# @libraries.each do |library| %>
<!--    <li>-->
      <%#= link_to library.name, library_path(library) %>
<!--    </li>-->
  <%# end %>
<!--</ul>-->

<%#= form_tag libraries_path, method: :get do %>
<!--  <label for="sort_by">Sort by:</label>-->
  <%#= select_tag :sort_by, options_for_select(['', 'books_asc', 'books_desc']) %>
  <%#= submit_tag "Sort" %>
<%# end %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Name <%= link_to "↑↓", libraries_path(sort_by: (@sort_by == "name_asc" ? "name_desc" : "name_asc"),name: @name), class: "fa fa-sort" %><%= form_tag libraries_path, method: :get do %>
        <%= text_field_tag :name, @name, placeholder: "Search by name" %>
        <% if @name.present? %>
          <%= link_to "×", libraries_path, class: "remove-search" %>
        <% end %>
        <%= submit_tag "Search" %>
      <% end %></th>
    <th>Book count <%= link_to "↑↓", libraries_path(sort_by: (@sort_by == "books_asc" ? "books_desc" : "books_asc"), name: @name), class: "fa fa-sort" %></th>
    <th>Genre count <%= link_to "↑↓", libraries_path(sort_by: (@sort_by == "genres_asc" ? "genres_desc" : "genres_asc"), name: @name), class: "fa fa-sort" %></th>
    <th>Link</th>
  </tr>
  </thead>
  <tbody>
  <% @libraries.each do |library| %>
    <tr>
      <td><%= library.id %></td>
      <td><%= library.name %></td>
      <td><%= library.books_count %></td>
      <td><%= library.genres_count %></td>
      <td><%= link_to "link", library_path(library) %></td>

    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @libraries %>
<%= link_to 'Download CSV', downloader_csv_path(format: :csv) %>
<%= link_to 'Download PDF', downloader_pdf_path(format: :pdf) %>
<br>
<%= link_to 'New Libraries', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with(model: @library, url: libraries_path) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :year_of_creation %>
    <%= form.text_field :year_of_creation %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
    <%#= form.text_field :year_of_creation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/show.html.erb
<h1><%= @library.name %></h1>

<% if @library.image.attached?%>
<%= image_tag @library.image.variant(resize_to_limit: [150, 150]).processed%>
<% end %>
<p><strong>Address:</strong> <%= @library.location %></p>

<p><strong>Year of creation:</strong> <%= @library.year_of_creation %></p>

<p><strong>Street address:</strong> <%= @library.street_address %></p>

<p><strong>Zip code:</strong> <%= @library.zip_code %></p>


<h2>Books</h2>
<ul>
  <% @books.each do |book| %>
    <li><%= book.title %></li>
  <% end %>
</ul>

<h2>Reader Cards user name</h2>
<ul>
  <% @reader_cards.each do |reader_card| %>
    <li><%= reader_card.user.name %></li>
  <% end %>
</ul>
<%= link_to "Download Library Report", downloader_pdf_library_path(@library) %>
<%= link_to 'List library', libraries_path %>
<%= link_to 'Edit library', edit_library_path%>
<%= button_to "Destroy this library", @library, method: :delete %>