config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout' }, as: 'user_sessions'
  root to: 'pages#home'

  resources :genres
  resources :users
  resources :authors
  resources :reader_cards
  resources :libraries
  resources :books
  get '/home', to: 'pages#home'
  get 'downloads/csv', to: 'downloader#csv', as: 'downloader_csv'
  get 'downloads/pdf', to: 'downloader#pdf', as: 'downloader_pdf'
  get '/libraries/:id/download_report', to: 'downloader#pdf_library', as: 'downloader_pdf_library'
  get '/users/:id/download_report', to: 'downloader#pdf_user', as: 'downloader_pdf_user'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>

  </head>
  <script>
      setTimeout(function() {
          $('.alert').fadeOut('slow');
      }, 3000);
  </script>
  <body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <script>
      document.addEventListener('DOMContentLoaded', function() {
          var alerts = document.querySelectorAll('.alert');
          alerts.forEach(function(alert) {
              setTimeout(function() {
                  alert.style.display = 'none';
              }, 3000);
          });
      });
  </script>

  <div class="user-info">
    <% if user_signed_in? %>
      <div class="user-email">Welcome <%= current_user.email %></div>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out-btn" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>
  <div class="header">
    <%= link_to 'Home', home_path %>
    <%= link_to 'List author', authors_path %>
    <%= link_to 'List books', books_path %>
    <%= link_to 'List reader_card', reader_cards_path %>
    <%= link_to 'List user', users_path %>
    <%= link_to 'List genre', genres_path %>
    <%= link_to 'List library', libraries_path %>
  </div>
    <%= yield %>
  </body>
</html>